import type { Neighborhood } from "./types";

export const neighborhoods: Neighborhood[] = [
  {
    id: "aeroclube",
    name: "Aeroclube",
    x: 38.30,
    y: 14.70,
    developments: 18,
  },
  {
    id: "intermares",
    name: "Intermares",
    x: 53.19,
    y: 14.70,
    developments: 23,
  },
  {
    id: "bessa",
    name: "Bessa",
    x: 53.52,
    y: 27.54,
    developments: 31,
  },
  {
    id: "areia-dourada",
    name: "Areia Dourada",
    x: 39.85,
    y: 32.28,
    developments: 12,
  },
  {
    id: "jardim-luna",
    name: "Jardim Luna",
    x: 57.96,
    y: 36.03,
    developments: 16,
  },
  {
    id: "bancarios",
    name: "Bancários",
    x: 33.63,
    y: 46.10,
    developments: 14,
  },
  {
    id: "miramar",
    name: "Miramar",
    x: 45.30,
    y: 46.90,
    developments: 20,
  },
  {
    id: "manaira",
    name: "Manaíra",
    x: 56.85,
    y: 46.10,
    developments: 28,
  },
  {
    id: "formosa",
    name: "Formosa",
    x: 29.85,
    y: 63.69,
    developments: 11,
  },
  {
    id: "jardim-oceania",
    name: "Jardim Oceania",
    x: 43.63,
    y: 63.69,
    developments: 26,
  },
  {
    id: "tambau",
    name: "Tambaú",
    x: 57.19,
    y: 55.59,
    developments: 24,
  },
  {
    id: "tambauzinho",
    name: "Tambauzinho",
    x: 57.74,
    y: 63.69,
    developments: 15,
  },
  {
    id: "portal-do-sol",
    name: "Portal do Sol",
    x: 27.74,
    y: 75.93,
    developments: 13,
  },
  {
    id: "poco",
    name: "Poço",
    x: 38.30,
    y: 77.12,
    developments: 9,
  },
  {
    id: "cabo-branco",
    name: "Cabo Branco",
    x: 50.85,
    y: 74.94,
    developments: 27,
  },
  {
    id: "ponta-de-campina",
    name: "Ponta de Campina",
    x: 61.30,
    y: 74.55,
    developments: 17,
  },
  {
    id: "ponta-de-matos",
    name: "Ponta de Matos",
    x: 46.63,
    y: 86.80,
    developments: 10,
  },
  {
    id: "camboinha",
    name: "Camboinha",
    x: 56.19,
    y: 86.99,
    developments: 8,
  },
  {
    id: "ponta-dos-seixas",
    name: "Ponta dos Seixas",
    x: 66.52,
    y: 86.27,
    developments: 7,
  },
];